repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

# ruff
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.284
  hooks:
    - id: ruff
      # uncomment next line to enable autofix
      # args: [ --fix, --exit-non-zero-on-fix ]
