from py2winapp import build

options = dict(
    main_file_name="main.py",  # required
    python_version="3.9.7",  # required
    show_console=True,
    input_dir="source",
    # ignore_patterns = ...
    # requirements_file = ...
    build_dir = 'program',
    # icon_file = ...
    # download_dir = ...
    # pydist_sub_dir_name = ...
    build_source_sub_dir_name = 'source'
    # extra_pip_install_args = ...
)

build(**options)
